### ISSUE TITLE
Requires documentation and examples

### ISSUE THREAD

**Issue by Jesuqq** [jubicoy/easyconfig#1]
Hi,
this library looks very promising although I would appreciate some documentation and basic examples. Thank you!

**Comment by vilppuvuorinen** [comment]
README has been updated with usage examples. You are welcome to suggest improvmenets to the documentation in the form of a PR if the documentation does not appear to be sufficient.

**Comment by Jesuqq** [comment]
Thank you for making open source community better! Will close now.
